version: 1.0.{build}

image: Visual Studio 2017

init:
  - ps: '[System.IO.File]::AppendAllText("C:\Windows\System32\drivers\etc\hosts", "`n93.184.221.200  api.nuget.org")'

install:
  - cmd: ping api.nuget.org

before_build:
  - cmd: dotnet restore
  - cmd: nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
  project: NameSorterAssessment.sln

test_script:
  - cmd: dotnet test OpenPractice.Tests\Libs\NameSort\Unit\
  - cmd: dotnet test OpenPractice.Tests\Libs\NameSort\Integration\
  - cmd: dotnet test OpenPractice.Tests\Libs\NameSort\Stress\

